SELECT
    PRODUCT_CODE,
    SUM((PRICE * SALES_AMOUNT)) AS SALES
FROM
    OFFLINE_SALE SALE
    LEFT JOIN PRODUCT PRODUCT
    ON SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY
    PRODUCT_CODE
ORDER BY
    SALES DESC, PRODUCT_CODE;