-- 잡은 BASS와 SNAPPER의 수를 출력하는 SQL 문
SELECT
    COUNT(ID) AS FISH_COUNT
FROM
    FISH_INFO AS FISH
LEFT JOIN
    FISH_NAME_INFO AS NAME
ON 
    FISH.FISH_TYPE = NAME.FISH_TYPE
WHERE
    NAME.FISH_NAME = 'BASS' OR NAME.FISH_NAME = 'SNAPPER';