-- 종류 별로 가장 큰 물고기의 ID, 물고기 이름, 길이를 출력하는 SQL 문
-- 물고기의 ID에 대해 오름차순 정렬

WITH MAX_LENGTH AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH 
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
)

SELECT
    FISH.ID,
    INFO.FISH_NAME,
    FISH.LENGTH
FROM FISH_INFO AS FISH
    LEFT JOIN FISH_NAME_INFO AS INFO
    ON
        FISH.FISH_TYPE = INFO.FISH_TYPE
    INNER JOIN MAX_LENGTH ML
    ON FISH.LENGTH = ML.MAX_LENGTH AND FISH.FISH_TYPE = ML.FISH_TYPE 
ORDER BY
    FISH.ID;