-- 2022년 10월에 작성된 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일을 조회
-- 결과는 댓글 작성일을 기준으로 오름차순 정렬해주시고, 댓글 작성일이 같다면 게시글 제목을 기준으로 오름차순 정렬

SELECT
    TITLE,
    BOARD.BOARD_ID AS BOARD_ID,
    REPLY_ID,
    REPLY.WRITER_ID AS WRITER_ID,
    REPLY.CONTENTS AS CONTENTS,
    DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM
    USED_GOODS_REPLY REPLY
    LEFT JOIN
    USED_GOODS_BOARD BOARD
    ON
    REPLY.BOARD_ID = BOARD.BOARD_ID
WHERE
    YEAR(BOARD.CREATED_DATE) = 2022
    AND
    MONTH(BOARD.CREATED_DATE) = 10
ORDER BY
    REPLY.CREATED_DATE, TITLE  
;